### ISSUE TITLE
Help! Segfaults and out of memory everywhere

### ISSUE THREAD

**Issue by icebarf** [cstef7/acc#2] opened 2021-10-19 05:23 UTC
Hi I have 16 GigaBytes of RAM yet the compiler says it ran out of memory? Why is that!

**Comment by cstef7** [comment] 2021-10-19 07:21
This is an issue of your specific machine. Try compiling the following program:
```c
#include <stdio.h>
int main(){puts("amogus");}
```
Alternatively, try closing other programs before running the compiler. An out-of-memory error might also be caused by page thrashing. There are known bugs regarding out-of-memory errors and the fact that they can occasionally occur as a result of unrelated events (broken motherboard, bus error etc.). However, these errors are unrecoverable and attempts to continue compilation would be futile.

**Closed as completed by cstef7** 2021-10-19 07:21 UTC
